<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class unitOwned extends Model
{
    protected $table = 'unit_owned';
    protected $fillable = [
        'data_id',
        'vin2',
        'driver_name2',
        'driver_dob2',
        'driver_license2',
        'driver_license_state2',
        'vehicle_year2',
        'vehicle_make2',
        'stated_value2',
        'vin3',
        'driver_name3',
        'driver_dob3',
        'driver_license3',
        'driver_license_state3',
        'vehicle_year3',
        'vehicle_make3',
        'stated_value3',
        'vin4',
        'driver_name4',
        'driver_dob4',
        'driver_license4',
        'driver_license_state4',
        'vehicle_year4',
        'vehicle_make4',
        'stated_value4',
        'vin5',
        'driver_name5',
        'driver_dob5',
        'driver_license5',
        'driver_license_state5',
        'vehicle_year5',
        'vehicle_make5',
        'stated_value5',
        'vin6',
        'driver_name6',
        'driver_dob6',
        'driver_license6',
        'driver_license_state6',
        'vehicle_year6',
        'vehicle_make6',
        'stated_value6',
        'vin7',
        'driver_name7',
        'driver_dob7',
        'driver_license7',
        'driver_license_state7',
        'vehicle_year7',
        'vehicle_make7',
        'stated_value7',
        'vin8',
        'driver_name8',
        'driver_dob8',
        'driver_license8',
        'driver_license_state8',
        'vehicle_year8',
        'vehicle_make8',
        'stated_value8',
        'vin9',
        'driver_name9',
        'driver_dob9',
        'driver_license9',
        'driver_license_state9',
        'vehicle_year9',
        'vehicle_make9',
        'stated_value9',
        'vin10',
        'driver_name10',
        'driver_dob10',
        'driver_license10',
        'driver_license_state10',
        'vehicle_year10',
        'vehicle_make10',
        'stated_value10',
    ];
    use HasFactory;
}
